#!/usr/bin/env python3
""" Regex filter """
from pymongo import MongoClient


def find_holberton_schools(mongo_collection):
	'''  lists all documents with name starting by Holberton in the collection school.
	'''
	regex_pattern = "^Holberton"
    	holberton_schools = mongo_collection.find({"name": {"$regex": regex_pattern, "$options": "i"}})
	for school in holberton_schools:
		print(school)

if __name__ == "__main__":
	client = MongoClient('mongodb://127.0.0.1:27017')
	db = client.my_db
	collection = db.school
	find_holberton_schools(collection)
